### ISSUE TITLE
Add support for template matching on captured video

### ISSUE THREAD

**Issue by phckopper** [balena-io-hardware/autokit-interface-sw#2]
When testing graphical user interfaces, it'd be nice to be able to automate checking whether a certain symbol is being displayed. For instance, we could trigger an image to be displayed on balena-dash and want to verify that it's shown correctly. It could also be used as a trigger for certain events, like the appearance of certain logos or status symbols.

This feature is called [template matching](https://docs.opencv.org/3.4/de/da9/tutorial_template_matching.html) and could be implemented with [OpenCV node.js bindings](https://www.npmjs.com/package/opencv).

**Comment by phckopper** [comment]
@rcooke-warwick can you check whether such an improvement is in scope for the project?

**Comment by phckopper** [comment]
As discussed in the Autokit Weekly with @rcooke-warwick, it's in scope for the project, however it should be developed in a separate repo and imported here

**Comment by rcooke-warwick** [comment]
I think that this feature should actually be something that is part of the test, rather than the autokit or its interface. The autokit should give you the captured data, but its up to the test to do the matching. It should be an interface, rather than a "tester".
